spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://localhost:8070/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  devtools:
    livereload:
      port: 35732

