spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: "actor-service-api"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8070/"
  devtools:
    livereload:
      port: 35733

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic