spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: "director-service-api"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8070/"
  devtools:
    livereload:
      port: 35734
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true