server:
  port: 8070
spring:
  application:
    name: "config-server"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/harunaydemir001/cinema-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
