spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: actor
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: "actor-service"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8070/"
  devtools:
    livereload:
      port: 35730


